[platformio]
src_dir = src

[common]
platform = https://github.com/platformio/platform-espressif32.git
framework = espidf
platform_packages =
    platformio/framework-espidf@3.50500.0
monitor_speed = 115200

board_build.partitions = meshtastic-4mb.csv
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 655360

# Default to using the main defaults file
board_build.idf_sdkconfig_defaults = sdkconfig.defaults

extra_scripts =
    post:extra_script_sizecheck.py

build_flags =
    -fno-exceptions 
    -Os
    -ffunction-sections 
    -fdata-sections
    -Wl,--gc-sections
    -DCORE_DEBUG_LEVEL=0

[env:esp32s3]
extends = common
board = esp32-s3-devkitc-1
board_upload.maximum_size = 655360
board_upload.flash_address = 0x650000
upload_command  = esptool.py -p $UPLOAD_PORT write_flash ${this.board_upload.flash_address} $SOURCE
board_build.cmake_extra_args = -DENABLE_BLE_OTA=ON -DENABLE_WIFI_OTA=ON


[env:esp32]
extends = common
board = esp32dev
board_upload.maximum_size = 655360
board_upload.flash_address = 0x260000
upload_command  = esptool.py -p $UPLOAD_PORT write_flash ${this.board_upload.flash_address} $SOURCE
board_build.cmake_extra_args = -DENABLE_BLE_OTA=ON -DENABLE_WIFI_OTA=ON

# ESP32-S2: No Bluetooth support
[env:esp32s2]
extends = common
board = esp32-s2-saola-1
board_upload.maximum_size = 655360
board_upload.flash_address = 0x260000
upload_command  = esptool.py -p $UPLOAD_PORT write_flash ${this.board_upload.flash_address} $SOURCE
board_build.cmake_extra_args = -DENABLE_BLE_OTA=OFF -DENABLE_WIFI_OTA=ON

# Untested - 4MB Flash Assumed
[env:esp32c3]
extends = common
board = esp32-c3-devkitm-1
board_upload.maximum_size = 655360
board_upload.flash_address = 0x260000
upload_command  = esptool.py -p $UPLOAD_PORT write_flash ${this.board_upload.flash_address} $SOURCE
board_build.cmake_extra_args = -DENABLE_BLE_OTA=ON -DENABLE_WIFI_OTA=OFF

# Untested - 4MB Flash Assumed
[env:esp32c6]
extends = common
board = esp32-c6-devkitm-1
board_upload.maximum_size = 655360
board_upload.flash_address = 0x260000
upload_command  = esptool.py -p $UPLOAD_PORT write_flash ${this.board_upload.flash_address} $SOURCE
board_build.cmake_extra_args = -DENABLE_BLE_OTA=ON -DENABLE_WIFI_OTA=OFF
